version: '2'
services:
    cafeteria-app:
        image: cafeteria
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://cafeteria-postgresql:5432/cafeteria
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cafeteria-postgresql:
        extends:
            file: postgresql.yml
            service: cafeteria-postgresql
